//	HYPE.documents["react 首次渲染-不自动播放"]

(function () {
  (function m() {
    function k(a, b, c, d) {
      var e = !1;
      null == window[a] &&
        (null == window[b]
          ? ((window[b] = []),
            window[b].push(m),
            (a = document.getElementsByTagName("head")[0]),
            (b = document.createElement("script")),
            (e = l),
            false == !0 && (e = ""),
            (b.type = "text/javascript"),
            "" != d &&
              ((b.integrity = d), b.setAttribute("crossorigin", "anonymous")),
            (b.src = e + "/" + c),
            a.appendChild(b))
          : window[b].push(m),
        (e = !0));
      return e;
    }
    var l = "/js/react-render",
      f = "/images/react-render",
      g = "react_render_container";
    if (false == !1)
      try {
        for (
          var c = document.getElementsByTagName("script"), a = 0;
          a < c.length;
          a++
        ) {
          var d = c[a].src,
            b = null != d ? d.indexOf("/react-render.js") : -1;
          if (-1 != b) {
            l = d.substr(0, b);
            break;
          }
        }
      } catch (p) {}
    c = navigator.userAgent.match(/MSIE (\d+\.\d+)/);
    c = parseFloat(c && c[1]) || null;
    d =
      !0 == (null != window.HYPE_668F || null != window.HYPE_dtl_668F) ||
      false == !0 ||
      (null != c && 10 > c);
    a = !0 == d ? "HYPE-668.full.min.js" : "HYPE-668.thin.min.js";
    c = !0 == d ? "F" : "T";
    d = d ? "" : "";
    if (
      false == !1 &&
      ((a = k("HYPE_668" + c, "HYPE_dtl_668" + c, a, d)),
      false == !0 &&
        (a =
          a ||
          k("HYPE_w_668", "HYPE_wdtl_668", "HYPE-668.waypoints.min.js", "")),
      false == !0 &&
        (a = a || k("Matter", "HYPE_pdtl_668", "HYPE-668.physics.min.js", "")),
      a)
    )
      return;
    d = window.HYPE.documents;
    if (null != d[f]) {
      b = 1;
      a = f;
      do f = "" + a + "-" + b++;
      while (null != d[f]);
      for (
        var e = document.getElementsByTagName("div"), b = !1, a = 0;
        a < e.length;
        a++
      )
        if (e[a].id == g && null == e[a].getAttribute("HYP_dn")) {
          var b = 1,
            h = g;
          do g = "" + h + "-" + b++;
          while (null != document.getElementById(g));
          e[a].id = g;
          b = !0;
          break;
        }
      if (!1 == b) return;
    }
    b = [];
    b = [];
    e = {};
    h = {};
    for (a = 0; a < b.length; a++)
      try {
        (h[b[a].identifier] = b[a].name),
          (e[b[a].name] = eval("(function(){return " + b[a].source + "})();"));
      } catch (n) {
        window.console && window.console.log(n),
          (e[b[a].name] = function () {});
      }
    c = new window["HYPE_668" + c](
      f,
      g,
      {
        10: {
          p: 1,
          n: "%E5%9C%BA%E6%99%AF%E5%8D%81%E4%BA%8C.png",
          g: "272",
          t: "@1x",
        },
        2: { p: 1, n: "%E5%9C%BA%E6%99%AF%E4%B8%89.png", g: "165", t: "@1x" },
        "-2": { n: "blank.gif" },
        3: { p: 1, n: "%E5%9C%BA%E6%99%AF%E5%9B%9B.png", g: "174", t: "@1x" },
        11: {
          p: 1,
          n: "%E5%9C%BA%E6%99%AF%E5%8D%81%E4%B8%89.png",
          g: "281",
          t: "@1x",
        },
        4: { p: 1, n: "%E5%9C%BA%E6%99%AF%E4%BA%94.png", g: "190", t: "@1x" },
        5: { p: 1, n: "%E5%9C%BA%E6%99%AF%E4%B8%83.png", g: "209", t: "@1x" },
        12: {
          p: 1,
          n: "%E5%9C%BA%E6%99%AF%E5%8D%81%E5%9B%9B.png",
          g: "290",
          t: "@1x",
        },
        6: { p: 1, n: "%E5%9C%BA%E6%99%AF%E5%85%AB.png", g: "218", t: "@1x" },
        13: {
          p: 1,
          n: "%E5%9C%BA%E6%99%AF%E5%8D%81%E4%BA%94.png",
          g: "299",
          t: "@1x",
        },
        7: { p: 1, n: "%E5%9C%BA%E6%99%AF%E4%B9%9D.png", g: "236", t: "@1x" },
        "-1": { n: "PIE.htc" },
        0: {
          p: 1,
          n: "%E5%9C%BA%E6%99%AF%E4%B8%80.jpg",
          g: "147",
          o: true,
          t: "@1x",
        },
        8: { p: 1, n: "%E5%9C%BA%E6%99%AF%E5%8D%81.png", g: "245", t: "@1x" },
        1: {
          p: 1,
          n: "%E5%9C%BA%E6%99%AF%E4%BA%8C.jpg",
          g: "156",
          o: true,
          t: "@1x",
        },
        9: {
          p: 1,
          n: "%E5%9C%BA%E6%99%AF%E5%8D%81%E4%B8%80.png",
          g: "263",
          t: "@1x",
        },
      },
      l,
      [],
      e,
      [
        { n: "\u4e00", o: "1", X: [0] },
        { n: "\u4e8c", o: "150", X: [1] },
        { n: "\u4e09", o: "159", X: [2] },
        { n: "\u56db", o: "168", X: [3] },
        { n: "\u4e94", o: "177", X: [4] },
        { n: "\u4e94\u70b9\u4e94", o: "193", X: [5] },
        { n: "\u4e03", o: "203", X: [6] },
        { n: "\u516b", o: "212", X: [7] },
        { n: "\u516b\u70b9\u4e94", o: "221", X: [8] },
        { n: "\u4e5d", o: "228", X: [9] },
        { n: "\u5341", o: "239", X: [10] },
        { n: "\u5341\u70b9\u4e94", o: "248", X: [11] },
        { n: "\u5341\u4e00", o: "255", X: [12] },
        { n: "\u5341\u4e8c", o: "266", X: [13] },
        { n: "\u5341\u4e09", o: "275", X: [14] },
        { n: "\u5341\u56db", o: "284", X: [15] },
        { n: "\u5341\u4e94", o: "293", X: [16, 17] },
      ],
      [
        {
          o: "3",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["334", "336", "335"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 0,
          v: {
            334: {
              h: "147",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 4,
              k: "div",
              b: 10,
              d: 41,
              c: 261,
            },
            335: {
              b: 10,
              z: 3,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
            336: {
              b: 10,
              z: 2,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#00FDFF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "beginWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
          },
        },
        {
          o: "155",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["338", "337", "339"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 1,
          v: {
            337: {
              b: 10,
              z: 2,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#00FDFF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "beginWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
            338: {
              h: "156",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 5,
              k: "div",
              b: 10,
              d: 111,
              c: 261,
            },
            339: {
              b: 10,
              z: 3,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
          },
        },
        {
          o: "164",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["342", "340", "341"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 2,
          v: {
            340: {
              b: 10,
              z: 2,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#00FDFF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "beginWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
            341: {
              b: 10,
              z: 3,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
            342: {
              h: "165",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 6,
              k: "div",
              b: 10,
              d: 181,
              c: 261,
            },
          },
        },
        {
          o: "173",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["344", "343", "345"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 3,
          v: {
            343: {
              b: 10,
              z: 3,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#00FDFF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "beginWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
            344: {
              h: "174",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              k: "div",
              b: 10,
              d: 251,
              c: 521,
            },
            345: {
              b: 10,
              z: 4,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
          },
        },
        {
          o: "182",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [{ a: [{}], B: "\u81ea\u5b9a" }],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["347", "346", "348"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 4,
          v: {
            346: {
              b: 10,
              z: 4,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#00FDFF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "beginWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
            347: {
              h: "190",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 3,
              k: "div",
              b: 10,
              d: 321,
              c: 521,
            },
            348: {
              b: 10,
              z: 5,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
          },
        },
        {
          o: "198",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["349", "350", "351"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 5,
          v: {
            349: {
              h: "190",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 3,
              k: "div",
              b: 10,
              d: 321,
              c: 521,
            },
            350: {
              b: 10,
              z: 4,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FF40FF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "completeWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
            351: {
              b: 10,
              z: 5,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
          },
        },
        {
          o: "208",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["354", "353", "352"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 6,
          v: {
            352: {
              b: 10,
              z: 7,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
            353: {
              b: 10,
              z: 6,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FF40FF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "completeWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
            354: {
              h: "209",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              k: "div",
              b: 10,
              d: 419,
              c: 711,
            },
          },
        },
        {
          o: "217",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["355", "356", "357"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 7,
          v: {
            355: {
              h: "218",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 6,
              k: "div",
              b: 10,
              d: 419,
              c: 711,
            },
            356: {
              b: 10,
              z: 7,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#00FDFF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "beginWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
            357: {
              b: 10,
              z: 8,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
          },
        },
        {
          o: "226",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["360", "359", "358"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 8,
          v: {
            358: {
              b: 10,
              z: 8,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
            359: {
              b: 10,
              z: 7,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FF40FF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "completeWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
            360: {
              h: "218",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 6,
              k: "div",
              b: 10,
              d: 419,
              c: 711,
            },
          },
        },
        {
          o: "233",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["362", "361", "363"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 9,
          v: {
            361: {
              b: 10,
              z: 9,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#00FDFF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "beginWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
            362: {
              h: "236",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 8,
              k: "div",
              b: 10,
              d: 419,
              c: 851,
            },
            363: {
              b: 10,
              z: 10,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
          },
        },
        {
          o: "244",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["366", "364", "365"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 10,
          v: {
            364: {
              b: 10,
              z: 10,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#00FDFF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "beginWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
            365: {
              b: 10,
              z: 11,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
            366: {
              h: "245",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 9,
              k: "div",
              b: 10,
              d: 419,
              c: 851,
            },
          },
        },
        {
          o: "253",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["367", "369", "368"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 11,
          v: {
            367: {
              h: "245",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 9,
              k: "div",
              b: 10,
              d: 419,
              c: 851,
            },
            368: {
              b: 10,
              z: 11,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
            369: {
              b: 10,
              z: 10,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FF40FF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "completeWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
          },
        },
        {
          o: "260",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["371", "372", "370"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 12,
          v: {
            370: {
              b: 10,
              z: 13,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
            371: {
              h: "263",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 11,
              k: "div",
              b: 10,
              d: 419,
              c: 991,
            },
            372: {
              b: 10,
              z: 12,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FF40FF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "completeWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
          },
        },
        {
          o: "271",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["375", "374", "373"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 13,
          v: {
            373: {
              b: 10,
              z: 14,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
            374: {
              b: 10,
              z: 13,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FF40FF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "completeWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
            375: {
              h: "272",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 12,
              k: "div",
              b: 10,
              d: 419,
              c: 991,
            },
          },
        },
        {
          o: "280",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["378", "376", "377"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 14,
          v: {
            376: {
              b: 10,
              z: 14,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FF40FF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "completeWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
            377: {
              b: 10,
              z: 15,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
            378: {
              h: "281",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 12,
              k: "div",
              b: 10,
              d: 419,
              c: 991,
            },
          },
        },
        {
          o: "289",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["379", "381", "380"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 15,
          v: {
            379: {
              h: "290",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 13,
              k: "div",
              b: 10,
              d: 419,
              c: 991,
            },
            380: {
              b: 10,
              z: 16,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
            381: {
              b: 10,
              z: 15,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FF40FF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "completeWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
          },
        },
        {
          o: "328",
          p: "600px",
          a: 30,
          Y: 320,
          Z: 568,
          b: 30,
          cA: false,
          c: "#FFF",
          L: [],
          bY: 1,
          d: 320,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["383", "382", "384"],
          n: "iPhone",
          _: 16,
          v: {
            382: {
              b: 10,
              z: 16,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FF40FF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "completeWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
            383: {
              h: "299",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 15,
              k: "div",
              b: 10,
              d: 419,
              c: 991,
            },
            384: {
              b: 10,
              z: 17,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
          },
        },
        {
          o: "298",
          p: "600px",
          cA: false,
          Y: 1024,
          Z: 768,
          L: [],
          c: "#FFF",
          bY: 1,
          d: 1024,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: ["386", "385", "387"],
          n: "\u672a\u547d\u540d\u5e03\u5c40",
          _: 17,
          v: {
            385: {
              b: 10,
              z: 16,
              K: "Solid",
              c: 90,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FF40FF",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 1 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "completeWork<br>",
              x: "visible",
              I: "Solid",
              a: 346,
              y: "preserve",
              J: "Solid",
            },
            386: {
              h: "299",
              p: "no-repeat",
              x: "visible",
              a: 10,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 15,
              k: "div",
              b: 10,
              d: 419,
              c: 991,
            },
            387: {
              b: 10,
              z: 17,
              K: "Solid",
              c: 31,
              L: "Solid",
              d: 15,
              aS: 6,
              M: 1,
              bD: "none",
              N: 1,
              aT: 6,
              dB: "button",
              O: 1,
              g: "#FFFB00",
              aU: 6,
              P: 1,
              aV: 6,
              j: "absolute",
              k: "div",
              aI: 4,
              aJ: 4,
              aK: 4,
              aL: 4,
              A: "#A0A0A0",
              B: "#A0A0A0",
              Z: "break-word",
              r: "inline",
              C: "#A0A0A0",
              D: "#A0A0A0",
              t: 13,
              aA: { a: [{ d: 1.1, p: 1, g: 1, f: 2 }] },
              F: "center",
              G: "#000",
              aP: "pointer",
              w: "back<br>",
              x: "visible",
              I: "Solid",
              a: 466,
              y: "preserve",
              J: "Solid",
            },
          },
        },
      ],
      {},
      h,
      {},
      null,
      false,
      true,
      -1,
      true,
      true,
      false,
      true,
      true
    );
    d[f] = c.API;
    document.getElementById(g).setAttribute("HYP_dn", f);
    c.z_o(this.body);
  })();
})();
